version: "3.9"
   
services:
  ddns:
    env_file: .env
    build: ./cardboard-ddns
    command: ./ddns-client.sh --hostname cardboard.cafe --api-key ${API_KEY} --url ddns.cardboard.cafe --secret ${SECRET}
  ssl:
    image: certbot/certbot
    container_name: certbot
    ports:
        - "80:80"
    volumes:
        - certbot-etc:/etc/letsencrypt
    command: certonly --email ptjob6@gmail.com --non-interactive --agree-tos --no-eff-email -d cardboard.cafe --standalone --preferred-challenges http -v
  cafe:
    build: ./cardboard-cafe
    volumes:
        - type: volume
          source: certbot-etc
          target: /etc/letsencrypt
          volume:
            nocopy: true
    depends_on:
        - ssl
    ports:
        - "443:443"
    working_dir: /home/express
    command: npm start

volumes: 
    certbot-etc: